## Question A

Matrix A has 2 rows and 3 columns. It is a 2 by 3 matrix
Matrix B has 3 rows and 2 columns. It is a 3 by 2 matrix

## Question B 

The mulptiplication is possible. It can be AB OR BA

## Question C

Explained multiplication
AB11 = (2*1) + (-1*-2) + (3*5) = 2+2+15 = 19
AB12 = (2*2) + (-1*0) + (3*-3) = 4+0+(-9) = -5
AB21 = (0*1) + (4*-2) + (1*5) = 0+(-8)+5 = -3
AB22 = (0*2) + (4*0) + (1*-3) = 0+0+(-3) = -3

Result matrix AB=
19 -5
-3 -3

## Question D

In [2]:
import numpy as np

A = np.array([[2, -1, 3], [0, 4, 1]])
B = np.array([[1, 2], [-2, 0], [5, -3]])

# Matrix multiplication AB
AB = np.dot(A, B)
print("Matrix AB:")
print(AB)

# Matrix multiplication BA
BA = np.dot(B, A)
print("\nMatrix BA:")
print(BA)

Matrix AB:
[[19 -5]
 [-3 -3]]

Matrix BA:
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
