##  Question 1

In [3]:
import numpy as np
matrix = np.random.randint(1, 50, size=(6,6))
print('Array (6 x 6):\n',  matrix)

Array (6 x 6):  [[10  9  6 18  8  2]
 [26  2 26  4 11 23]
 [25 49  5 36  2 33]
 [ 2 26 44 49  2 31]
 [28 48 19 13 25  7]
 [36 35 24 34 21  7]]


## Question 2

In [6]:
print("First 2 rows:")
print (matrix[:2])
print("\nLast 3 columns:")
print(matrix[0:, -3:])
print("\nEven numbers in the array:")
print(matrix[matrix % 2 == 0])

First 2 rows:
[[10  9  6 18  8  2]
 [26  2 26  4 11 23]]

Last 3 columns:
[[18  8  2]
 [ 4 11 23]
 [36  2 33]
 [49  2 31]
 [13 25  7]
 [34 21  7]]

Even numbers in the array:
[10  6 18  8  2 26  2 26  4 36  2  2 26 44  2 28 48 36 24 34]


## Question 3

In [8]:
print("Reshaped 3D array:")
reshaped_matrix = matrix.reshape(3, 2, 6)
print(reshaped_matrix)


print("\nFlattened 1D array:")
print(reshaped_matrix.flatten())

Reshaped 3D array:
[[[10  9  6 18  8  2]
  [26  2 26  4 11 23]]

 [[25 49  5 36  2 33]
  [ 2 26 44 49  2 31]]

 [[28 48 19 13 25  7]
  [36 35 24 34 21  7]]]

Flattened 1D array:
[10  9  6 18  8  2 26  2 26  4 11 23 25 49  5 36  2 33  2 26 44 49  2 31
 28 48 19 13 25  7 36 35 24 34 21  7]


## Question 4

In [24]:
print("4x4 Identity Matrix:")
identity_matrix = np.eye(4)
print(identity_matrix)

print("\n")
diagonal_matrix = np.diag(np.arange(10, 50, 10))
print(diagonal_matrix)

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


## Question 5

In [17]:
print("3x4 matrix:")
array1 = np.random.randint(1, 10, size=(3,4))
print(array1)
print("\n4x3 matrix:")
array2 = np.random.randint(1, 10, size=(4,3))
print(array2)

print("\n")
print("Matrix Multiplication Result:")
result = np.matmul(array1, array2)
print(result)
res = np.dot(array1, array2)
print(res)

3x4 matrix:
[[5 4 9 8]
 [1 6 1 7]
 [2 3 4 2]]

4x3 matrix:
[[8 4 4]
 [6 4 3]
 [4 5 9]
 [3 2 4]]


Matrix Multiplication Result:
[[124  97 145]
 [ 69  47  59]
 [ 56  44  61]]
[[124  97 145]
 [ 69  47  59]
 [ 56  44  61]]


## Question 6


In [27]:
def arr_ops():
   rows = int(input('Enter number of rows: '))
   cols = int(input('Enter number of columns: '))
   arr = []
   for i in range(rows):
      for j in range (cols):
          arr.append(int(input(f"Value at row {rows} and columns {cols}")))
   array = np.array(arr).reshape(rows, cols)
   print("Array:")
   print(array)
 